--ORA tables
create table cash_point(
                id 			        int 	generated by default as identity primary key
            ,	point_name          varchar(200)    not null unique
            ,   point_account_num   varchar(20)     not null unique
            );


create table cash_operation(
                            id 			        int 	        generated by default as identity primary key
                        ,   cash_point          int             not null references cash_point(id)
                        ,   account_num         varchar(50)     not null
                        ,   sum_doc             decimal(18,2)   not null
                        ,   direction           varchar(20)     not null
                        ,   state               varchar(20)     not null
                        ,   refuse_reason       varchar(2000)
                        ,   purpose             varchar(2000)   not null
                    );