--ORA tables
create table cash_document_in(
                    id 			int 			generated by default as identity primary key
				,	debet       int             not null
				,	credit      int             not null
				,   doc_sum     decimal(18,2)   not null
				,   doc_date    date            not null
				,   exec_info   varchar(2000)
				,   state       varchar(20)     not null
				);